version: "3.9"

networks:
  app_network:
    driver: bridge

services:
  mysql:
    image: mysql:8.0.26
    container_name: ${APP_NAME}_mysql
    hostname: mysql
    restart: unless-stopped
    tty: true
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - app_network

  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    ports:
      - "8080:80"
    restart: always
    environment:
    WORDPRESS_DB_HOST: mysql:${DB_PORT}
    WORDPRESS_DB_USER: ${DB_USERNAME}
    WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - app_network
